discourse/discourse-solved

config/locales/client.de.yml, config/locales/server.de.yml
The plugin was lacking german translations for the client and server. This PR adds those.
=> Added german translations for client and server interface

config/locales/client.pt_BR.yml, config/locales/server.pt_BR.yml
=> Add Brazilian Portuguese locale

config/locales/client.fi.yml, config/locales/server.fi.yml
A simple translation of the English locale into a Finnish one.
=> Finnish locale

config/locales/client.fa.yml
as this is the real locale name for Persian language in discourse.
=> change locale name from fa to fa_IR,

plugin.rb
Adding server events to assist other plugins in building interoperable features. See further: https://meta.discourse.org/t/topic-list-previews/41630/529?u=angus
=> Add accept and unaccept solution events

plugin.rb
https://meta.discourse.org/t/hiding-unsolved-checkbox-on-pinned-topics/58438/5
=> Remove empty checkbox for closed/archived topics

assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6, plugin.rb
https://meta.discourse.org/t/option-to-move-accepted-answer-to-the-top/58386/16?u=david_taylor
Makes use of PostCooked to build the quote UI the same way as in the rest of Discourse.
=> Quote accepted answer at top

config/locales/client.fi.yml, config/locales/server.fi.yml
a typo fix, an improvement and two new keys
=> Update Finnish locale

config/locales/server.en.yml, config/settings.yml, plugin.rb, spec/integration/solved_spec.rb
https://meta.discourse.org/t/automatically-close-solved-topics-after-n-hours/58383
=> FEATURE: Add `solved_topics_auto_close_hours` site setting.

config/locales/server.es.yml
https://github.com/discourse/discourse-solved/commit/ed8b0103f63f1fdc788f8d404de24c6c1b8350db
=> Added `solved_topics_auto_close_hours`

config/locales/client.fa_IR.yml
adding the missing lines to the Persian translation
=> some missing lines

spec/integration/solved_spec.rb
https://github.com/discourse/discourse/pull/5122
=> Make tests work with Rails 5.1.

plugin.rb
This is an SEO trick, intended to make results from Discourse forms more "clickable" by promising a solution at the other end of the link.
https://meta.discourse.org/t/suggestion-add-checkmark-for-solved-threads-to-the-topic-title-as-well/33813
=> Add schema.org QAPage metadata

plugin.rb
Fixes
https://meta.discourse.org/t/support-schema-org-qapage-and-google-rich-results/33813/14?u=notriddle
=> Move the QAPage Question into mainEntity

test/javascripts/acceptance/discourse-solved-test.js.es6
(issue introduced in https://github.com/discourse/discourse-solved/pull/105/files#diff-a2b6a1622bdc1ddf5f4fd546319bbe4c0216528d6e9a0648d105a65a9933d2eeR10)
=> DEV: Fix a linting error and work around a test issue

assets/stylesheets/mobile/solutions.scss, assets/stylesheets/solutions.scss
=> FIX: update solved filter due to core changes

plugin.rb
The solved feature will be enabled on a random category and a random post will get marked as "accepted answer" on it.
=> DEV: create a sample solved topic for `dev:populate` rake task.

assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
Depends on https://github.com/discourse/discourse/pull/13813
=> UX: Add quick search suggestion entries

plugin.rb
Related PR in core: https://github.com/discourse/discourse/pull/14078
=> UX: do not show composer education message if the post is whisper

plugin.rb
We need a proper fix, but this stops the bleeding for now.
Wrapped code related to `register_topic_list_preload_user_ids` in
a `respond_to?(:register_topic_list_preload_user_ids)` block because
this API is not available in beta or stable versions of Discourse.
=> FIX: Stop register_topic_list_preload_user_ids from breaking old versions

assets/javascripts/discourse/routes/user-activity-solved.js.es6, config/locales/client.en.yml, test/javascripts/acceptance/user-activity-solved-test.js.es6
When a user doesn't have posts accepted as solutions, we'll be showing this:
=> FEATURE: improve blank page syndrome

test/javascripts/acceptance/discourse-solved-test.js.es6
See https://github.com/discourse/eslint-config-discourse/commit/4f7aba06c03fdd22bb26669aeb8ed4af3127c409
=> DEV: Update code for eslint object-shorthand-rule

assets/javascripts/discourse/connectors/topic-navigation/no-answer.hbs, assets/javascripts/discourse/connectors/topic-navigation/no-answer.js.es6, config/locales/client.en.yml
Implements a notice that will show for old topics with no accepted
answers.
Needs https://github.com/discourse/discourse/pull/15081 to be merged first.
=> FEATURE: Show notice if user can accept an answer

assets/javascripts/discourse/connectors/topic-navigation/no-answer.js.es6
Related to: https://github.com/discourse/discourse/pull/15683
=> FIX: Do not render no-answer nudge on mobile

test/javascripts/acceptance/user-activity-solved-test.js
My bad, I've just merged a PR that doesn't pass linting checks.
=> DEV: fix linting issue

.github/workflows/plugin-linting.yml, .github/workflows/plugin-tests.yml, .rubocop.yml, .streerc, Gemfile, Gemfile.lock, app/lib/first_accepted_post_solution_validator.rb, db/migrate/20191209095548_ensures_unique_accepted_answer_post_id.rb, db/migrate/20221121223417_rename_badges.rb, plugin.rb, spec/components/composer_messages_finder_spec.rb, spec/components/post_revisor_spec.rb, spec/fabricators/solved_hook_fabricator.rb, spec/integration/solved_spec.rb, spec/lib/first_accepted_post_solution_validator_spec.rb, spec/models/site_spec.rb, spec/requests/list_controller_spec.rb, spec/requests/topics_controller_spec.rb, spec/serializers/topic_answer_mixin_spec.rb, spec/serializers/user_card_serializer_spec.rb
Adds syntax_tree configuration and formats code
=> DEV: Introduce syntax_tree for ruby formatting

config/locales/client.en.yml, plugin.rb
Adds a single API scope for accepting or unaccepting a solution.
=> FEATURE: Add API Scopes

assets/javascripts/discourse/initializers/extend-for-solved-button.js, plugin.rb, spec/requests/topics_controller_spec.rb
When displaying the accepted answer in the OP.
=> FIX: Respect "display name on posts" site setting

plugin.rb, spec/requests/topics_controller_spec.rb
https://meta.discourse.org/t/alignment-of-schema-org-markup-between-qa-solved-dfp-core/279510
=> FIX: make JSON_LD schema consistent with our microdata in core

assets/javascripts/discourse/initializers/extend-for-solved-button.js
Need an app event here for a customer theme
=> DEV: add appEvent for solution-toggled

assets/javascripts/discourse/components/solved-unaccept-answer-button.gjs, assets/javascripts/discourse/connectors/bread-crumbs-right/solved-status-filter.js, assets/javascripts/discourse/initializers/extend-for-solved-button.js, assets/javascripts/discourse/routes/user-activity-solved.js, test/javascripts/acceptance/discourse-solved-post-menu-test.js, test/javascripts/acceptance/discourse-solved-test.js, test/javascripts/acceptance/discourse-solved-widget-post-menu-test.js, test/javascripts/acceptance/user-activity-solved-test.js
mostly new i18n imports and qunit-dom
=> DEV: Minor code cleanup

assets/javascripts/discourse/initializers/add-topic-list-class.js
…to replace a deprecated topic-list-item customization
=> DEV: Use `topic-list-item-class` transformer

assets/javascripts/discourse/components/solved-accept-answer-button.gjs, assets/javascripts/discourse/components/solved-unaccept-answer-button.gjs, assets/javascripts/discourse/connectors/user-summary-stat/solved-count.hbs, assets/javascripts/discourse/initializers/extend-for-solved-button.js, assets/stylesheets/mobile/solutions.scss, db/fixtures/001_badges.rb
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
=> DEV: Update more deprecated Font Awesome icon names

test/javascripts/acceptance/discourse-solved-test.js
Preparation for https://github.com/discourse/discourse/pull/32082
Followup to fc2d1a290c31eb6f415b346f8dcd01e79fad8041
=> DEV: Update selector in test

README.md
This reverts commit 0ab400221d1d48e9c0fe13c02d6249afccc75884.
=> Revert "DEV: Deprecate the plugin (#382)"
