discourse/discourse-solved

- plugin.rb
Adds a custom filter to TopicQuery which allows you to filter by solved or unsolved.
So you can do, for example:
https://my.forum/latest?solved=true
or
https://my.forum/latest?solved=true
This is better than just using the search filters, because you can see more than 50 topics in the list.
This depends on [discourse 74d4209](https://github.com/discourse/discourse/commit/74d4209d24adabfa94f8c0bfc513b14ebbdfadb8) so currently this code will break for anyone on 1.7 stable.
> Allow filtering by solved or unsolved

- plugin.rb
@SamSaffron my previous PR which was merged breaks discourse-solved on any Discourse before 1.8.0.beta6 (e.g. if someone is running 1.7 stable). This PR adds a version check before running the new code.
> Check discourse version before adding TopicQuery filters

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
Adds a setting which allows displaying an "Empty Box" on topics which are eligible to receive an answer, but have not yet been solved. Disabled by default, so should not affect existing setups.
> Added empty box icon to unsolved topics

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
Added addDiscoveryQueryParam for `solved` parameter.
https://meta.discourse.org/t/making-filters-work-without-reload/58049
> Allow linking to filters within the site

- plugin.rb
Sorry @SamSaffron, got another one for you. 
Using 'true'/'false' in the query variables wasn't working, because Ember interpreted the default as False (wheras we need 3 states: solved, unsolved & all). I've changed the strings to 'solved'/'unsolved' to work around that issue.
https://discuss.emberjs.com/t/boolean-query-params/4301
> Change parameters from true/false to solved/unsolved.

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
https://meta.discourse.org/t/option-to-move-accepted-answer-to-the-top/58386/25
> UX: Show configurable length excerpt when quoting the solution

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
Topic-status was moved in https://github.com/discourse/discourse/commit/f105d721297c2d2df2d9c19c674ba8563015df84 on 14th November (1.7.0beta7). Given 1.6 is no longer supported, I think it should be ok to fix this, and stop the deprecation warnings in the javascript console
> FIX: deprecation warning on topic-status

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
- assets/stylesheets/solutions.scss
- plugin.rb
- test/javascripts/acceptance/discourse-solved-test.js.es6
> This PR resolves https://meta.discourse.org/t/remove-quote-of-the-solution-if-solved-quote-length-is-set-to-zero/61106
This new feature hides the excerpt for accepted answers if `solved_quote_length` has been set to zero, as per the discussion linked above.
---
**`solved_quote_length := 0`**
---
**`solved_quote_length := 10`**
---
> FEATURE: hide excerpt if 'solved_quote_length' is set to zero

- assets/javascripts/discourse/connectors/topic-after-cooked/solved-panel.hbs
- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
- assets/stylesheets/solutions.scss
- config/locales/client.en.yml
https://meta.discourse.org/t/button-with-checkmark-should-be-hidden-to-users-who-cant-unmark-correct-answers/79216
> UX: Improve button position and visibility.

- config/locales/server.en.yml
- db/fixtures/001_badges.rb
- plugin.rb
When plugin is installed, we should create helpdesk and tech support
badges.
Both badges should be disabled by default
> FEATURE: Add helpdesk and tech support badges

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
- config/locales/client.en.yml
- db/fixtures/002_web_hook_event_types.rb
- plugin.rb
- spec/fabricators/solved_hook_fabricator.rb
- spec/integration/solved_spec.rb
This feature will publish a post edit webhook event whenever a solution
is accepted or unaccepted.
I went ahead and used the existing post-edit webhook because all the
post custom fields for the solved plugin are already included in the
post-edit serializer.
> FEATURE: Publish WebHook event when solving/unsolving

- plugin.rb
Duration is a new keyword argument on Topic#set_or_create_timer and is not yet available in stable Discourse
https://github.com/discourse/discourse-solved/commit/329d8aff30bf21e59e2c2ddcbc0e5a51bc8ef70d
> FIX: plugin backwards compatibility with Discourse 2.4

- config/locales/server.en.yml
The copy change makes it clear that when set to 0 topics will not be auto closed. Possibly I'm the only person who has been confused by the setting though. This is related to looking at issues mentioned here: https://meta.discourse.org/t/solved-topics-not-autoclosing/166708/12.
One thing to note with this setting is that it accepts a float, for example 0.1. When set to a float, the float will be displayed in the settings field, but Discourse will round it down to the nearest integer when using the setting. This means that setting it to anything less than 1 will prevent topics from being auto closed. I'm not sure if this needs to be fixed - I think it's too much detail to give in the setting's description though.
> Improve solved topics auto close hours description

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
- spec/integration/solved_spec.rb
Previously, we won't send any notification to original poster when a staff user marked a post as the solution behalf of OP.
> FEATURE: send notification to OP when staff marked a post as solution.

- assets/javascripts/discourse/connectors/bread-crumbs-right/solved-status-filter.hbs
- assets/javascripts/discourse/connectors/bread-crumbs-right/solved-status-filter.js.es6
There is no topic list to filter on the categories page, so we should not be rendering the solved filter there.
This also addresses two deprecation notices:
> UX: Do not render solved filter on categories page

- plugin.rb
- spec/integration/solved_spec.rb
Topic solved should be closed silently as system user involvement may be confusing.
In addition, old rescue block was dropped.
Meta: https://meta.discourse.org/t/discourse-encrypt-unable-to-see-close-message/135235
> FEATURE: silently auto close solved topic

- assets/javascripts/discourse/initializers/extend-for-solved-button.js.es6
- test/javascripts/acceptance/discourse-solved-test.js.es6
Merge after https://github.com/discourse/discourse/pull/11554
> DEV: Add acceptance tests for solved icon in full page search.

- plugin.rb
- spec/components/post_revisor_spec.rb
Moving a topic between categories did not update the 'Mark as solution' controls too. This fix applies only if the old and new category have different 'solved' settings.
> FIX: Refresh whole post stream when category changes

- plugin.rb
DO NOT MERGE UNTIL https://github.com/discourse/discourse/pull/11961 IS MERGED
> FIX: Update set_or_create_topic_timer to use duration_minutes keyword

- assets/stylesheets/solutions.scss
Before (note the link icon):
After:
> UX: Fixed solved alignment with buttons due to core changes

- config/settings.yml
- db/migrate/20210218022053_solved_fix_high_auto_close_topic_hours.rb
* Also add migration to cap current site settings for
solved_topics_auto_close_hours
to the max of 175000 if they are too high
See https://github.com/discourse/discourse/commit/e0f0fe5624298021bbbb7845c12bf1582767631d
> FIX: Add min/max values for auto close hours

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
- spec/components/composer_messages_finder_spec.rb
When replying on solved topic users will now see this education message:
This message can be disabled from site setting.
Meta reference: https://meta.discourse.org/t/rfe-for-solved-plugin-make-new-topic-more-obvious/177680/5?u=techapj
> FEATURE: show education message in composer when replying on solved topic

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
We've added two options on behalf of a client and I think they might be useful for a broader audience.
- Optionally disallow topic starters to select a solution (leaving that to staff or high trust level users).
- Make inserting QAPage schema markup optional since that is not always desired.
> Two extra options

- plugin.rb
We've been past the 2.7 release for a while now and silent_close
is in core; time to remove this fallback.
> DEV: Remove fallback to TopicTimer close type

- plugin.rb
- spec/serializers/user_card_serializer_spec.rb
The previous query which used custom fields performed a much more
complex and slower search.
> PERF: Use UserAction to count accepted answers

- app/serializers/concerns/topic_answer_mixin.rb
- config/locales/server.en.yml
`allow_accepted_answer` should be `allow_accepted_answers` (with an `s` at the end) in the `TopicAnswerMixin`.
The `enable_solved_tags` setting description seemed to be using the description intended for `allow_solved_on_all_topics`. Both descriptions have been updated.
> FIX: typo in mixin and incorrect setting description

- assets/stylesheets/solutions.scss
> UX: prevent solution text and icon from wrapping

- assets/javascripts/discourse/connectors/bread-crumbs-right/solved-status-filter.js.es6
A more involved transition / redirect was happening which sometimes
made Ember think it was an incomplete transition and threw an error.
> FIX: Do a transition to update 'solved' queryparam

- assets/javascripts/discourse/connectors/topic-navigation/no-answer.hbs
- assets/javascripts/discourse/connectors/topic-navigation/no-answer.js.es6
The dismissed state will be stored in local storage because noticeId is
present now.
Merge after https://github.com/discourse/discourse/pull/15570
> FIX: Add a noticeId to store state

- assets/javascripts/discourse/connectors/topic-navigation/no-answer.js
This was adding 2s to every topic-view test when the solved plugin was loaded
> DEV: Skip UI delay in test mode

- spec/lib/first_accepted_post_solution_validator_spec.rb
See https://github.com/discourse/discourse/pull/18437, we are removing any references to enable_personal_messages in core and using only personal_message_enabled_groups, which requires auto groups to be assigned in certain specs for them to keep working.
> DEV: Fix specs for personal_message_enabled_groups setting

- config/locales/server.en.yml
- db/fixtures/001_badges.rb
- db/migrate/20221121223417_rename_badges.rb
* Updates SQL for existing badges ("Helpdesk" and "Tech Support")
* Converts badges into non-editable system badges
* Stops using translated badge names in DB which can result in duplicate badges when the default locale changes
* Updates the copy of the existing badges
* Adds two new badges
> Improve badges

- config/locales/client.en.yml
- plugin.rb
This PR adds a title that appears when hovering over solved notifications in the UI.
Screenshot:
> FIX: Add title to solved notifications

- assets/javascripts/discourse/initializers/extend-for-solved-button.js
- plugin.rb
Hide the accept solution button if a solution has been accepted already.
After accepting solution (the user is OP):
After accepting solution (the user is not OP):
After accepting solution:
> UX: Tweak 'Solution' button design

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
- spec/integration/solved_spec.rb
Many consumers of Discourse solve may want solved topics to show up more
prominently in search. New setting (default off) allows bumping these topics
to the top.
> FEATURE: prioritize_solved_topics_in_search to prioritize solved topics

- plugin.rb
- spec/fabricators/extend_topic_fabricator.rb
- spec/integration/solved_spec.rb
**Context** 
Advanced search using `status:unsolved` is supposed to return all topics/posts that have the `solved` plugin enabled and have a status of unsolved.
**Problem**
Advanced search using `status:unsolved` is also returning results from topics/posts that don't have the `solved` plugin enabled.
**Solution**
Fix the SQL query for `status:unsolved` to ignore topics/posts that also have `custom_topic_fields` and only search for those that belong to a category where the plugin is enabled.
> FIX: Search bug for status:unsolved returns topics from non-solution enabled categories

- assets/javascripts/discourse/connectors/bread-crumbs-right/solved-status-filter.js
- assets/stylesheets/solutions.scss
FIX: do not show solved/unsolved filter when editing category
Before:
After:
UX: add spacing for solved/unsolved filter dropdown
Before:
After:
> FIX: do not show solved/unsolved filter when editing category

- app/serializers/concerns/topic_answer_mixin.rb
- plugin.rb
- spec/integration/solved_spec.rb
Ensures we remove the solution when the post marked as the solution is deleted.
DEV: Added `IS_ACCEPTED_ASNWER_CUSTOM_FIELD` constant.
DEV: Refactored the `PostSerializer` for better readability.
PERF: Improved the `TopicViewSerializer`'s performance by looking up the `accepted_answer_post_info` from the stream first.
Internal ref. dev/112251
> FIX: delete solution with post

- assets/javascripts/discourse/connectors/bread-crumbs-right/solved-status-filter.js
As it's currently implemented, the fallback is essential here. `this` in a static method is `undefined`, and therefore cannot have an owner.
Unfortunately this plugin outlet does not seem to be tested in the plugin's own test suite. Core's test suite picked up this issue.
Followup to 3a0b46da7aa48e27e51c74e90b42c2083d89b4d5
> FIX: Correct getOwner import

- assets/javascripts/discourse/connectors/user-summary-stat/solved-count.hbs
Followup to 8352a79145505763ed9ac23820e1cb219519a3e5
> FIX: Solved count on user profile

- assets/javascripts/discourse/connectors/user-summary-stat/solved-count.hbs
Adds a missing class to apply styling to the user profile solved stat
Before:
After:
> UX: add `linked-stat` class to profile stat

- config/locales/client.en.yml
- config/settings.yml
This is so the plugins settings are better categorized in the site settings UI.
> DEV: Change settings root from plugins: to discourse_solved

- spec/lib/first_accepted_post_solution_validator_spec.rb
In https://github.com/discourse/discourse/pull/24740, `min_trust_to_create_topic` site setting was replaced by `create_topic_allowed_groups`. This PR replaces the former, deprecated one, with the latter.
> DEV: Replace deprecated min_trust_to_create_post

- spec/components/post_revisor_spec.rb
We're updating core to change TL based access settings to be group based. This requires some updates of tests to work correctly. (The existing test setup gives false positives.)
Related: https://github.com/discourse/discourse/pull/24257
> DEV: Update test setup to work with auto groups

- app/lib/accepted_answer_cache.rb
- app/lib/guardian_extensions.rb
- config/locales/server.en.yml
- config/settings.yml
- db/post_migrate/20240116100023_fill_accept_all_solutions_allowed_groups_based_on_deprecated_setting.rb
- plugin.rb
- spec/lib/guardian_extensions_spec.rb
New setting is accept_all_solutions_allowed_groups,
c.f. https://meta.discourse.org/t/changes-coming-to-settings-for-giving-access-to-features-from-trust-levels-to-groups/283408
Also move guardian extensions and accepted_answer_cache into other files,
this refactor makes for easier testing and makes things
more organised, the guardian extensions had no testing
whatsoever and I need some to make the TL -> group change.
> DEV: Change accept_all_solutions_trust_level to group setting

- .discourse-compatibility
- plugin.rb
- spec/integration/solved_spec.rb
Those can be used in /filter route.
Depends on https://github.com/discourse/discourse/pull/26770
Internal ref. /t/127278
> FEATURE: add new custom status filters

- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
- spec/integration/solved_spec.rb
When a topic is unsolved, it should have an option, defined in the settings, to change its status to that state.
Fix assign changes when a topic was solved; previously, it changed the assignee.
> FEATURE: change status on unsolve & fix assign changes

- config/settings.yml
This PR adds the `admins` and `moderators` automatic groups to the `mandatory_values` field of 
the `accept_all_solutions_allowed_groups` setting so that they're always shown in setting:
We're doing this because admins and moderators can always accept a solution and it's not possible to remove the permission for them.
Internal topic: t/128143.
> UX: Add admins and moderators to `mandatory_values` for `accept_all_solutions_allowed_groups`

- config/locales/server.en.yml
Admins and mods can always accept solutions, even if not specified in the accept_all_solutions_allowed_groups setting.
> clarified that admins and mods can accept solutions

- plugin.rb
- spec/integration/solved_spec.rb
it would raise an error because we delete the topic before and we need the topic record to update various meta data.
This ensures we load the "deleted" version in such cases.
Internal ref - t/130797
> FIX: when deleting users with solved posts

- assets/javascripts/discourse/connectors/user-card-metadata/accepted-answers.hbs
in https://github.com/discourse/discourse/commit/d4ade75583c2c5ef51b09b1d154c305719bc8788 heading tags were removed from the usercard 
this also removes them from the accepted answer stat that the solved plugin adds to the usercard so it's formatted consistently
> A11Y: remove heading tag from usercard stat

- app/lib/guardian_extensions.rb
- config/settings.yml
- spec/lib/guardian_extensions_spec.rb
A while ago the `accept_all_solutions_allowed_groups` setting was introduced to replace the `accept_all_solutions_trust_level` setting and to make the plugin more flexible by allowing admins to choose groups that are allowed to accept solutions instead of trust levels.
The new group-based setting includes the TL4 group by default. However, removing the TL4 group from the setting doesn't actually remove TL4 users permission to accept solution.
The reason for this bug is that the `can_accept_answer?` guardian method calls `can_perform_action_available_to_group_moderators?` which always allows TL4 users to perform category moderator actions:
https://github.com/discourse/discourse/blob/56524f4bdf9d45eddf7967ccead169ec6dd6cbb8/lib/guardian/topic_guardian.rb#L342-L348
This PR fixes the bug by …
> FIX: Don't allow TL4 users to unconditionally accept solutions

- app/lib/plugin_initializers/assigned_reminder_exclude_solved.rb
- plugin.rb
- spec/integration/solved_spec.rb
requires https://github.com/discourse/discourse-assign/pull/598
> FEATURE: Add modifier to update the assigned count and exclude solved topics

- assets/javascripts/discourse/connectors/after-topic-status/solved-status.gjs
- assets/javascripts/discourse/initializers/extend-for-solved-button.js
…and simplify other conditions (`can_have_answer` is true only if `solved_enabled` and `empty_box_on_unsolved` are also true)
> FIX: Use both possible `*_answer` attributes

- assets/javascripts/discourse/connectors/after-topic-status/solved-status.gjs
…in the new topic-status implementation (using the next `@context` from https://github.com/discourse/discourse/pull/30940)
This roughly matches the old implementation (but there it was displayed in some places but not in others mostly because of implementation details/bugs)
> DEV: Display unsolved icon only on the topic list

- app/lib/guardian_extensions.rb
- plugin.rb
- spec/integration/solved_spec.rb
- spec/lib/guardian_extensions_spec.rb
- spec/serializers/user_card_serializer_spec.rb
Pretty straightforward, this ensures we don't allow users to mark a post as a solution in a PM.
This also ensures we don't count solutions in topics that were converted to a PM.
Internal ref t/146766
> FIX: don't allow or count solutions in PMs

- assets/stylesheets/solutions.scss
Padding around the span version can cause misalignment. Also moved some old variables over to the current default ones and moved away from px spacing.
| Before | After |
|--------|--------|
| ![CleanShot 2025-03-26 at 16 15 24](https://github.com/user-attachments/assets/7bac0768-f6af-4d6a-a5a2-1d49964aeb5a) | ![CleanShot 2025-03-26 at 16 13 57@2x](https://github.com/user-attachments/assets/d916d884-dd64-4e75-bfb4-f6a181a9173b) |
> UX: fix misalignment for non-admin and anon + move to variable use

- app/controllers/discourse_solved/answer_controller.rb
- spec/requests/answer_controller_spec.rb
Simplify the solved_answers_controller_run_rate_limiter modifier to provide 
only a generic interface, allowing other plugins to implement specific 
rate limiting logic without modifying the core plugin.
> FEATURE: Provide generic modifier interface for rate limiting.

- plugin.rb
- spec/models/directory_item_spec.rb
Special thanks to [Moin](https://meta.discourse.org/u/moin/summary) for pointing this out.
If John created a post which is a solution in March, the user directory would show that John solution = 1.
In April, if John has not solved a topic, he would still have solution = 1 in the user directory.
Screenshot to user directory /u (does not show bug, just a reference):
The directory column query needs to include users with 0 solutions, so that the value would be updated.
> FIX: User directory for solutions should update when value changes from positive value to zero

- lib/discourse_solved/first_accepted_post_solution_validator.rb
- spec/lib/first_accepted_post_solution_validator_spec.rb
When fixing https://github.com/discourse/discourse-solved/pull/377, we uncovered another bug where the existing check does not remember to exclude the first solution itself.
This PR 
- makes sure to exclude the first solution when checking for an existing solution
- better tests -- the existing test does not accept the post prior to making the check.
> FIX: Exclude the first solution itself when checking if an existing solution

- test/javascripts/acceptance/user-activity-solved-test.js
Re-enables the tests disabled in 1d038963fdfa290dd77dc95371403d31eace5611, now that https://github.com/discourse/discourse/pull/33455 has been merged
minor change in behavior, as when there's no body text `.empty-state__body` no longer exists (used to render empty)
> DEV: re-enable and update empty state tests

- assets/javascripts/discourse/components/solved-accepted-answer.gjs
This adds an aria-label based on the state of the button and also moves the title to the button rather than the icon. 
I also noticed that `aria-expanded` was rendering as `aria-expanded=""` which isn't helpful, we need a true/false string as the examples show here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-expanded
> A11Y: improve expand/collapse labeling on embedded solution post
